/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AwardsRouteImport } from './routes/awards'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as HobbiesRouteImport } from './routes/hobbies'
import { Route as MmsRouteImport } from './routes/mms'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as VenturesRouteImport } from './routes/ventures'
import { Route as VolunteeringRouteImport } from './routes/volunteering'
import { Route as MmsIndexRouteImport } from './routes/mms.index'
import { Route as MmsCapstoneRouteImport } from './routes/mms.capstone'
import { Route as MmsCoursesRouteImport } from './routes/mms.courses'
import { Route as MmsLabRouteImport } from './routes/mms.lab'
import { Route as MmsReflectionsRouteImport } from './routes/mms.reflections'
import { Route as MmsRotationsRouteImport } from './routes/mms.rotations'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AwardsRoute = AwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const HobbiesRoute = HobbiesRouteImport.update({
  id: '/hobbies',
  path: '/hobbies',
  getParentRoute: () => rootRouteImport,
} as any)
const MmsRoute = MmsRouteImport.update({
  id: '/mms',
  path: '/mms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const VenturesRoute = VenturesRouteImport.update({
  id: '/ventures',
  path: '/ventures',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteeringRoute = VolunteeringRouteImport.update({
  id: '/volunteering',
  path: '/volunteering',
  getParentRoute: () => rootRouteImport,
} as any)
const MmsIndexRoute = MmsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MmsRoute,
} as any)
const MmsCapstoneRoute = MmsCapstoneRouteImport.update({
  id: '/capstone',
  path: '/capstone',
  getParentRoute: () => MmsRoute,
} as any)
const MmsCoursesRoute = MmsCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => MmsRoute,
} as any)
const MmsLabRoute = MmsLabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => MmsRoute,
} as any)
const MmsReflectionsRoute = MmsReflectionsRouteImport.update({
  id: '/reflections',
  path: '/reflections',
  getParentRoute: () => MmsRoute,
} as any)
const MmsRotationsRoute = MmsRotationsRouteImport.update({
  id: '/rotations',
  path: '/rotations',
  getParentRoute: () => MmsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/awards': typeof AwardsRoute
  '/experience': typeof ExperienceRoute
  '/hobbies': typeof HobbiesRoute
  '/mms': typeof MmsRouteWithChildren
  '/research': typeof ResearchRoute
  '/resume': typeof ResumeRoute
  '/ventures': typeof VenturesRoute
  '/volunteering': typeof VolunteeringRoute
  '/mms/capstone': typeof MmsCapstoneRoute
  '/mms/courses': typeof MmsCoursesRoute
  '/mms/lab': typeof MmsLabRoute
  '/mms/reflections': typeof MmsReflectionsRoute
  '/mms/rotations': typeof MmsRotationsRoute
  '/mms/': typeof MmsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/awards': typeof AwardsRoute
  '/experience': typeof ExperienceRoute
  '/hobbies': typeof HobbiesRoute
  '/research': typeof ResearchRoute
  '/resume': typeof ResumeRoute
  '/ventures': typeof VenturesRoute
  '/volunteering': typeof VolunteeringRoute
  '/mms/capstone': typeof MmsCapstoneRoute
  '/mms/courses': typeof MmsCoursesRoute
  '/mms/lab': typeof MmsLabRoute
  '/mms/reflections': typeof MmsReflectionsRoute
  '/mms/rotations': typeof MmsRotationsRoute
  '/mms': typeof MmsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/awards': typeof AwardsRoute
  '/experience': typeof ExperienceRoute
  '/hobbies': typeof HobbiesRoute
  '/mms': typeof MmsRouteWithChildren
  '/research': typeof ResearchRoute
  '/resume': typeof ResumeRoute
  '/ventures': typeof VenturesRoute
  '/volunteering': typeof VolunteeringRoute
  '/mms/capstone': typeof MmsCapstoneRoute
  '/mms/courses': typeof MmsCoursesRoute
  '/mms/lab': typeof MmsLabRoute
  '/mms/reflections': typeof MmsReflectionsRoute
  '/mms/rotations': typeof MmsRotationsRoute
  '/mms/': typeof MmsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/awards'
    | '/experience'
    | '/hobbies'
    | '/mms'
    | '/research'
    | '/resume'
    | '/ventures'
    | '/volunteering'
    | '/mms/capstone'
    | '/mms/courses'
    | '/mms/lab'
    | '/mms/reflections'
    | '/mms/rotations'
    | '/mms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/awards'
    | '/experience'
    | '/hobbies'
    | '/research'
    | '/resume'
    | '/ventures'
    | '/volunteering'
    | '/mms/capstone'
    | '/mms/courses'
    | '/mms/lab'
    | '/mms/reflections'
    | '/mms/rotations'
    | '/mms'
  id:
    | '__root__'
    | '/'
    | '/awards'
    | '/experience'
    | '/hobbies'
    | '/mms'
    | '/research'
    | '/resume'
    | '/ventures'
    | '/volunteering'
    | '/mms/capstone'
    | '/mms/courses'
    | '/mms/lab'
    | '/mms/reflections'
    | '/mms/rotations'
    | '/mms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AwardsRoute: typeof AwardsRoute
  ExperienceRoute: typeof ExperienceRoute
  HobbiesRoute: typeof HobbiesRoute
  MmsRoute: typeof MmsRouteWithChildren
  ResearchRoute: typeof ResearchRoute
  ResumeRoute: typeof ResumeRoute
  VenturesRoute: typeof VenturesRoute
  VolunteeringRoute: typeof VolunteeringRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awards': {
      id: '/awards'
      path: '/awards'
      fullPath: '/awards'
      preLoaderRoute: typeof AwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hobbies': {
      id: '/hobbies'
      path: '/hobbies'
      fullPath: '/hobbies'
      preLoaderRoute: typeof HobbiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mms': {
      id: '/mms'
      path: '/mms'
      fullPath: '/mms'
      preLoaderRoute: typeof MmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ventures': {
      id: '/ventures'
      path: '/ventures'
      fullPath: '/ventures'
      preLoaderRoute: typeof VenturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteering': {
      id: '/volunteering'
      path: '/volunteering'
      fullPath: '/volunteering'
      preLoaderRoute: typeof VolunteeringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mms/': {
      id: '/mms/'
      path: '/'
      fullPath: '/mms/'
      preLoaderRoute: typeof MmsIndexRouteImport
      parentRoute: typeof MmsRoute
    }
    '/mms/capstone': {
      id: '/mms/capstone'
      path: '/capstone'
      fullPath: '/mms/capstone'
      preLoaderRoute: typeof MmsCapstoneRouteImport
      parentRoute: typeof MmsRoute
    }
    '/mms/courses': {
      id: '/mms/courses'
      path: '/courses'
      fullPath: '/mms/courses'
      preLoaderRoute: typeof MmsCoursesRouteImport
      parentRoute: typeof MmsRoute
    }
    '/mms/lab': {
      id: '/mms/lab'
      path: '/lab'
      fullPath: '/mms/lab'
      preLoaderRoute: typeof MmsLabRouteImport
      parentRoute: typeof MmsRoute
    }
    '/mms/reflections': {
      id: '/mms/reflections'
      path: '/reflections'
      fullPath: '/mms/reflections'
      preLoaderRoute: typeof MmsReflectionsRouteImport
      parentRoute: typeof MmsRoute
    }
    '/mms/rotations': {
      id: '/mms/rotations'
      path: '/rotations'
      fullPath: '/mms/rotations'
      preLoaderRoute: typeof MmsRotationsRouteImport
      parentRoute: typeof MmsRoute
    }
  }
}

interface MmsRouteChildren {
  MmsCapstoneRoute: typeof MmsCapstoneRoute
  MmsCoursesRoute: typeof MmsCoursesRoute
  MmsLabRoute: typeof MmsLabRoute
  MmsReflectionsRoute: typeof MmsReflectionsRoute
  MmsRotationsRoute: typeof MmsRotationsRoute
  MmsIndexRoute: typeof MmsIndexRoute
}

const MmsRouteChildren: MmsRouteChildren = {
  MmsCapstoneRoute: MmsCapstoneRoute,
  MmsCoursesRoute: MmsCoursesRoute,
  MmsLabRoute: MmsLabRoute,
  MmsReflectionsRoute: MmsReflectionsRoute,
  MmsRotationsRoute: MmsRotationsRoute,
  MmsIndexRoute: MmsIndexRoute,
}

const MmsRouteWithChildren = MmsRoute._addFileChildren(MmsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AwardsRoute: AwardsRoute,
  ExperienceRoute: ExperienceRoute,
  HobbiesRoute: HobbiesRoute,
  MmsRoute: MmsRouteWithChildren,
  ResearchRoute: ResearchRoute,
  ResumeRoute: ResumeRoute,
  VenturesRoute: VenturesRoute,
  VolunteeringRoute: VolunteeringRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
